import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const plantSchema = appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'plants',
      columns: [
        { name: 'plant_id', type: 'string' },
        { name: 'journal_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'strain', type: 'string' },
        { name: 'planted_date', type: 'string' },
        { name: 'growth_stage', type: 'string' },
        { name: 'height', type: 'number', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'image_url', type: 'string', isOptional: true },
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'location_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'profiles',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'username', type: 'string' },
        { name: 'avatar_url', type: 'string', isOptional: true },
        { name: 'bio', type: 'string', isOptional: true },
        { name: 'experience_level', type: 'string', isOptional: true }, 
        { name: 'preferred_grow_method', type: 'string', isOptional: true }, 
        { name: 'favorite_strains', type: 'string', isOptional: true }, 
        { name: 'growing_since', type: 'string', isOptional: true }, 
        { name: 'location', type: 'string', isOptional: true },
        { name: 'is_certified', type: 'boolean', isOptional: true },
        { name: 'certifications', type: 'string', isOptional: true }, 
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'grow_journals',
      columns: [
        { name: 'journal_id', type: 'string' }, 
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'title', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'plant_strain', type: 'string' },
        { name: 'start_date', type: 'string' }, 
        { name: 'status', type: 'string' }, 
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'journal_entries',
      columns: [
        { name: 'entry_id', type: 'string' }, 
        { name: 'journal_id', type: 'string', isIndexed: true },
        { name: 'content', type: 'string' },
        { name: 'image_url', type: 'string', isOptional: true },
        { name: 'plant_stage', type: 'string', isOptional: true },
        { name: 'plant_height', type: 'number', isOptional: true }, 
        { name: 'water_amount', type: 'number', isOptional: true }, 
        { name: 'nutrients', type: 'string', isOptional: true },
        { name: 'temperature', type: 'number', isOptional: true }, 
        { name: 'humidity', type: 'number', isOptional: true }, 
        { name: 'light_hours', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'strains',
      columns: [
        { name: 'strain_id', type: 'string' }, 
        { name: 'name', type: 'string' },
        { name: 'type', type: 'string', isOptional: true }, 
        { name: 'thc_percentage', type: 'number', isOptional: true },
        { name: 'cbd_percentage', type: 'number', isOptional: true },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'flavors', type: 'string', isOptional: true }, 
        { name: 'effects', type: 'string', isOptional: true }, 
        { name: 'grow_difficulty', type: 'string', isOptional: true }, 
        { name: 'average_yield', type: 'string', isOptional: true },
        { name: 'flowering_time', type: 'number', isOptional: true }, 
        { name: 'created_by', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'grow_locations',
      columns: [
        { name: 'location_id', type: 'string' }, 
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'climate_zone', type: 'string', isOptional: true },
        { name: 'is_indoor', type: 'boolean' },
        { name: 'grow_medium', type: 'string', isOptional: true }, 
        { name: 'lighting_type', type: 'string', isOptional: true },
        { name: 'is_primary', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'notifications',
      columns: [
        { name: 'notification_id', type: 'string' }, 
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'sender_id', type: 'string', isOptional: true },
        { name: 'type', type: 'string' }, 
        { name: 'content', type: 'string', isOptional: true },
        { name: 'related_post_id', type: 'string', isOptional: true },
        { name: 'related_comment_id', type: 'string', isOptional: true },
        { name: 'is_read', type: 'boolean' },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'diary_entries',
      columns: [
        { name: 'entry_id', type: 'string' },
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'plant_id', type: 'string', isIndexed: true },
        { name: 'title', type: 'string' },
        { name: 'content', type: 'string' },
        { name: 'image_url', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
});
